version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    pre_build:
      - python -m sphinx -b linkcheck docs/source/ $READTHEDOCS_OUTPUT/linkcheck

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
