version: 2

formats: all

sphinx:
  configuration: docs/source/conf.py


build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    install:
      - pip install --upgrade pip
      - pip install --group 'docs'
    pre_build:
      - python -m sphinx -b linkcheck docs/source/ $READTHEDOCS_OUTPUT/linkcheck
