---
name: Publish Packages

on:
  release:
    types: [published]

env:
  UV_VERSION: 0.9.16
  PYTHON_VERSION: 3.13

jobs:
  build-n-publish:
    name: Build Release Packages
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout Source Files
      id: checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Setup uv
      id: setup-uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7

    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Build Packages
      id: build-packages
      shell: bash
      run: uv build

    - name: Publish Release on PyPI
      id: publish-release-on-pypi
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # release/v1
